language: c
branches:
  except:
    gh-pages
compiler:
  - gcc
  - clang
os:
  - osx
  - linux
env:
  # Default build. Release.
  - BUILD_ARGS=""
  # Debug build
  - BUILD_ARGS="-DCMAKE_BUILD_TYPE=Debug"
  # Everything that's optional
  - BUILD_ARGS="-DENABLE_PDF_DOCS=On -DENABLE_IPV6=On -DENABLE_LUA=On"
  # Everything that's optional, in Debug-mode
  - BUILD_ARGS="-DENABLE_PDF_DOCS=On -DENABLE_IPV6=On -DENABLE_LUA=On -DCMAKE_BUILD_TYPE=Debug"
  # Everything that's optional, GTK3
  - BUILD_ARGS="-DENABLE_PDF_DOCS=On -DENABLE_IPV6=On -DENABLE_LUA=On -DGTK_BUILD_TYPE=GTK3"
  # Everything that's optional, GTK3 in Debug-mode
  - BUILD_ARGS="-DENABLE_PDF_DOCS=On -DENABLE_IPV6=On -DENABLE_LUA=On -DGTK_BUILD_TYPE=GTK3 -DCMAKE_BUILD_TYPE=Debug"
  # IPV6 + system libnet
  - BUILD_ARGS="-DENABLE_IPV6=On -DBUNDLED_LIBNET=Off"
  # IPV6 + bundled libnet
  - BUILD_ARGS="-DENABLE_IPV6=On -DSYSTEM_LIBNET=Off"
  # system curl, only
  - BUILD_ARGS="-DBUNDLED_CURL=Off"
  # bundled curl, only
  - BUILD_ARGS="-DSYSTEM_CURL=Off"
  # system check, only
  - BUILD_ARGS="-DBUNDLED_LIBCHECK=Off"
  # bundled check, only
  - BUILD_ARGS="-DSYSTEM_LIBCHECK=Off"
  # Lua + system luajit
  - BUILD_ARGS="-DENABLE_LUA=On -DBUNDLED_LUAJIT=Off"
  # Lua + bundled luajit
  - BUILD_ARGS="-DENABLE_LUA=On -DSYSTEM_LUAJIT=Off"
  # Disable Gtk
  - BUILD_ARGS="-DENABLE_GTK=Off"
  # Disable Curses
  - BUILD_ARGS="-DENABLE_CURSES=Off"
  # Disable Curses and Gtk
  - BUILD_ARGS="-DENABLE_GTK=Off -DENABLE_CURSES=Off"
matrix:
  allow_failures:
    # We expect IPV6 + system libnet + ubuntu to fail :(
    - os: linux
      env: BUILD_ARGS="-DENABLE_IPV6=On -DBUNDLED_LIBNET=Off"
    # We expect system-only curl + ubuntu to fail :(
    - os: linux
      env: BUILD_ARGS="-DBUNDLED_CURL=Off"
  exclude:
    - os: osx
      env: BUILD_ARGS=""
    - os: osx
      env: BUILD_ARGS="-DCMAKE_BUILD_TYPE=Debug"
    - os: osx
      compiler: gcc
      env: BUILD_ARGS="-DENABLE_PDF_DOCS=On -DENABLE_IPV6=On -DENABLE_LUA=On"
    - os: osx
      compiler: gcc
      env: BUILD_ARGS="-DENABLE_PDF_DOCS=On -DENABLE_IPV6=On -DENABLE_LUA=On -DCMAKE_BUILD_TYPE=Debug"
    - os: osx
      compiler: gcc
      env: BUILD_ARGS="-DENABLE_PDF_DOCS=On -DENABLE_IPV6=On -DENABLE_LUA=On -DGTK_BUILD_TYPE=GTK3"
    - os: osx
      compiler: gcc
      env: BUILD_ARGS="-DENABLE_PDF_DOCS=On -DENABLE_IPV6=On -DENABLE_LUA=On -DGTK_BUILD_TYPE=GTK3 -DCMAKE_BUILD_TYPE=Debug"
    - os: osx
      env: BUILD_ARGS="-DENABLE_IPV6=On -DBUNDLED_LIBNET=Off"
    - os: osx
      env: BUILD_ARGS="-DENABLE_IPV6=On -DSYSTEM_LIBNET=Off"
    - os: osx
      env: BUILD_ARGS="-DBUNDLED_CURL=Off"
    - os: osx
      env: BUILD_ARGS="-DSYSTEM_CURL=Off"
    - os: osx
      env: BUILD_ARGS="-DBUNDLED_LIBCHECK=Off"
    - os: osx
      env: BUILD_ARGS="-DSYSTEM_LIBCHECK=Off"
    - os: osx
      env: BUILD_ARGS="-DENABLE_LUA=On -DBUNDLED_LUAJIT=Off"
    - os: osx
      env: BUILD_ARGS="-DENABLE_LUA=On -DSYSTEM_LUAJIT=Off"
    - os: osx
      env: BUILD_ARGS="-DENABLE_GTK=Off"
    - os: osx
      env: BUILD_ARGS="-DENABLE_CURSES=Off"
    - os: osx
      env: BUILD_ARGS="-DENABLE_GTK=Off -DENABLE_CURSES=Off"

before_install:
    - if [ ${TRAVIS_OS_NAME} = "linux" ]; then sudo apt-get update -qq; sudo apt-get install debhelper bison check cmake flex ghostscript libbsd-dev libcurl4-openssl-dev libgtk2.0-dev libltdl-dev libluajit-5.1-dev libncurses5-dev libnet1-dev libpcap-dev libpcre3-dev libssl-dev libgtk-3-dev; fi
    - if [ ${TRAVIS_OS_NAME} = "osx" ]; then brew update; brew install check curl; brew install ghostscript gtk+ gtk+3; brew install libidn libnet; brew install luajit openssl pcre rtmpdump; fi
script:
  - mkdir build && cd build && cmake -DENABLE_TESTS=On $BUILD_ARGS .. && make && make test_verbose
notifications:
  irc:
    channels:
      - "chat.freenode.net#ettercap-project"
    template:
      - "ettercap-build #%{build_number} (%{commit} by %{author}): %{message}"
      - "See details at %{build_url}"
  email: false
